config/routes.rb
Rails.application.routes.draw do
  devise_for :users 
  get 'home/show', to: 'home#show', as: 'show_home'
  get '/', to: 'events#index', as: 'home'
  get 'events/new', to: 'events#new', as: 'new_event'
  get '/user/:id/show', to: 'users#show', as: 'current_user'
  post '/events/new', to: 'events#create'
  get '/events/:id/show', to: 'events#show', as: 'event_show'
  post '/event/:id/suscribe', to: 'events#suscribe', as: 'suscribe'
  get '/event/:id/invite', to: 'events#share_invite', as:'invite'
  post '/event/invite', to: 'events#share_invite', as: 'share_invite'
  get '/users/:id/view_user', to: 'users#view_user', as: 'user_show'
  

  get 'events/show'
  get 'events/create'
  get 'home/index'

  resources :charges, only: [:new, :create]

 
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/event.rb
class Event < ApplicationRecord
    validates :description, presence: true
    validates :place, presence: true
    validates :date, presence: true
    
    belongs_to :creator, class_name: 'User'
    has_many :event_attendees
    has_many :attendees, through: :event_attendees
end

app/models/event_attendee.rb
class EventAttendee < ApplicationRecord
    validates :event_id, presence: true
    validates :attendee_id, presence: true
    belongs_to :event, class_name: 'Event'
    belongs_to :attendee, class_name: 'User', foreign_key: :attendee_id
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable #, :confirmable
  
  has_many :created_events, class_name: 'Event', foreign_key: :creator_id
  has_many :attending_events, through: :event_attendees, source: :event
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :authenticate_user!
end

app/controllers/charges_controller.rb
class ChargesController < ApplicationController
    def new
    
    end

    def create
        @amount = 500
        customer = Stripe::Customer.create(
            :email => params[:stripeEmail],
            :source  => params[:stripeToken]
        )

        charge = Stripe::Charge.create(
            :customer    => customer.id,
            :amount      => @amount,
            :description => 'Rails Stripe customer',
            :currency    => 'eur'
        )

        rescue Stripe::CardError => e
        flash[:error] = e.message
        redirect_to new_charge_path 
    end
end

app/controllers/events_controller.rb
require 'date'
class EventsController < ApplicationController
  def index
    @events = Event.all
  end

  def new

  end

  def show
    if current_user 
      @event = Event.find(params['id']) 
      @creator = User.find(@event.creator_id) 
      event_attending = EventAttendee.where(event_id: params[:id]) 
      @attendees = [] 
      event_attending.each do |a| 
        @attendees.push(User.find(a.attendee_id)) 
      end 
    else 
      flash[:alert] = "Veuillez vous connecter svp!" 
      redirect_to home_path 
    end
  end

  def create
    event = Event.create(description: params[:event][:description],
        place: params[:event][:place],
        date: Date.parse(params[:event][:date]),
        price: params[:event][:price].to_i
    )
    event.creator = User.find(current_user.id)
    
    if event.valid?
      event.save
      flash[:success] = "Evenement créer avec succès!"
      redirect_to current_user_path(event.id)
    else
      flash[:error] = "Champ invalide!"
      redirect_to new_event_path
    end
  end

  def suscribe
    attending = EventAttendee.new 
    event = Event.find(params[:id]) 
    attending.event = event 
    attending.attendee = User.find(current_user.id) 
      
    if !(attending.valid?) 
      redirect_to home_path
    end

    # Amount in cents
    @amount = event.price

    customer = Stripe::Customer.create(
      :email => params[:stripeEmail],
      :source  => params[:stripeToken]
    )

    charge = Stripe::Charge.create(
      :customer    => customer.id,
      :amount      => @amount,
      :description => 'Rails Stripe customer',
      :currency    => 'usd'
    )

    attending.save 
    flash[:success] = "Vous avez participez à l'évenement !"
    redirect_to event_show_path(event.id) 

    rescue Stripe::CardError => e
    flash[:error] = e.message
    redirect_to redirect_to event_show_path(event.id) 

  end

  def invite
    u = User.all 
    @potos = [] 
    @event = Event.find(params[:id]) 
    u.each do |x| 
      @potos.push(x.name) 
    end
  end

  def share_invite
    attending = EventAttendee.new 
    attending.event = Event.find(params['event']) 
    attending.attendee = User.find_by(name: params['potos']) 
    
    if attending.valid? 
      attending.save 
      redirect_to event_show_path(params['event']) 
    end
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    if user_signed_in?
      redirect_to show_home_path
    else
      redirect_to new_user_session_path
    end
  end

  def show
    
  
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    def show
        if current_user
            @events = Event.where(creator_id: current_user.id)
        else
            redirect_to new_event_path
        end
    end

    def view_user
        if params[:id] 
            @user = User.find(params[:id]) 
            @event_attended = EventAttendee.where(attendee_id: params['id']) 
            @events = [] 
            @event_attended.each do |e| 
                @events.push(Event.find(e.event_id)) 
            end 
        else 
            redirect_to new_event_path 
        end 
        event_attending = EventAttendee.where(attendee_id: params[:id]) 
        @attendees = [] 
        event_attending.each do |a| 
            @attendees.push(User.find(a.attendee_id)) 
        end
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/charges_helper.rb
module ChargesHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/charges/new.html.erb
<%= form_tag charges_path do %>
    <article>
      <% if flash[:error].present? %>
        <div id="error_explanation">
          <p><%= flash[:error] %></p>
        </div>
      <% end %>
      <label class="amount">
        <span>Amount: $5.00</span>
      </label>
    </article>
  
    <script src="https://checkout.stripe.com/checkout.js" class="stripe-button"
            data-key="<%= Rails.configuration.stripe[:publishable_key] %>"
            data-description="A month's subscription"
            data-amount="500"
            data-currency="eur"
            data-locale="auto">
    </script>
<% end %>

app/views/events/create.html.erb
<h1>Events#create</h1>
<p>Find me in app/views/events/create.html.erb</p>

app/views/events/index.html.erb
<div class="center jumbotron">
    <h1>Liste de tous les évènements</h1>
</div>

<% if flash[:success] %>
    <div class="alert alert-success alert-dismissible fade show" role="alert">
        <strong><%= flash[:success] %></strong> 
        <button type="button" class="close" data-dismiss="alert" aria-label="Close" >
            <span aria-hidden="true">&times;</span>
        </button>
    </div>
<% end %>

<% if flash[:alert] %>
    <div class="alert alert-warning alert-dismissible fade show" role="alert">
        <strong><%= flash[:alert] %></strong> 
        <button type="button" class="close" data-dismiss="alert" aria-label="Close" >
        <span aria-hidden="true">&times;</span>
        </button>
    </div>
<% end %>


<div class=" mt-5 p-5 offset-lg-2 col-lg-8 shadow">
    <div class="list-group">
        <% @events.each do |e| %>
            <a href="<%= event_show_path(e.id) %>" class="list-group-item list-group-item-action flex-column align-items-start">
                <div class="d-flex w-100 justify-content-between">
                    <h5 class="mb-1"><b><%= e.place %></b></h5>
                    <small><%= Date.parse(e.date.to_s).strftime('%a %d %b %Y') %></small>
                    <h5 class="mb-1"><b><%= e.price %> eur</b></h5>
                </div>
                <p class="mb-1">
                    <%= e.description %>
                </p>
            </a>
        <% end %>
    </div>
</div>

app/views/events/invite.html.erb
<div class="center jumbotron"> 
    <h1>Inviter un potos !</h1> 
</div> 
<div class="bg-light mt-5 p-5 offset-lg-2 col-lg-8 shadow"> 
    <%= form_tag share_invite_path, method: "post" do %> 
        <%= hidden_field_tag 'event', @event.id %> 
            <div class="form-group"> 
                <label for="potos">Liste des amis</label> <%= select_tag "potos", options_for_select(@potos), class: 'form-control' %> 
            </div> 
        <%= submit_tag "Envoyer", class: 'btn btn-primary' %> 
    <% end %> 
</div>

app/views/events/new.html.erb
<% provide(:title, "Create event") %>
 
 <div class="center jumbotron">
    <h1>Créer un évènement</h1>
 </div>
 
 <div class="bg-light mt-5 p-5 offset-lg-2 col-lg-8 shadow">
    <% if flash[:error] %>
        <div class="alert alert-danger alert-dismissible fade show" role="alert">
            <strong>Echec!</strong> <%= flash[:error] %>
            <button type="button" class="close" data-dismiss="alert" aria-label="Close" >
                <span aria-hidden="true">&times;</span>
            </button>
        </div>
    <% end %>
    <div class="row">
        <div class="col-md-8 offset-2 center">
            <%= form_for(:event, path: new_event_path) do |f| %>
                <div class="form-group">
                    <%= f.label :Description %>
                    <%= f.text_area :description, class: 'form-control' %>
                </div>
                <div class="form-group">
                    <%= f.label :Date %>
                    <%= f.date_field :date, class: 'form-control' %>
                </div>
        
                <div class="form-group">
                    <%= f.label :Place %>
                    <%= f.text_field :place, class: 'form-control' %>
                </div>

                <div class="form-group">
                    <%= f.label :Price %>
                    <%= f.text_field :price, class: 'form-control' %>
                </div>
        
                <%= f.submit "Créer l'évènement", class: "btn btn-primary" %>
            <% end %>
        </div>
    </div>
 </div>

app/views/events/show.html.erb
<div class="center jumbotron"> 
    <h1>creator: <%= @creator.email %></h1> 
    <h3> Place: <em><%= @event.place %></em> 
    </h3> <p><%= @event.description %></p>
    <small><%= Date.parse(@event.date.to_s).strftime('%a %d %b %Y') %></small><br> 
    <%= link_to "Retour", home_path, class: "btn btn-lg btn-success" %> 
    <% 
        i = 0 
        @attendees.each do |a| 
            if a.id == current_user.id 
                i += 1 
            end 
        end 
        if i > 0 
    %> 
            <%= link_to "Vous êtes déjà inscrit", '#', class: "btn btn-lg btn-info disabled" %> 
        <%else%> 

            <%= form_tag suscribe_path do %>
                <article>
                <% if flash[:error].present? %>
                    <div id="error_explanation">
                    <p><%= flash[:error] %></p>
                    </div>
                <% end %>
                <label class="amount">
                    <span>Participation: <%= @event.price.to_f/100 %> eur</span>
                </label>
                </article>
            
                <script src="https://checkout.stripe.com/checkout.js" class="stripe-button"
                        data-key="<%= Rails.configuration.stripe[:publishable_key] %>"
                        data-description="A month's subscription"
                        data-amount="500"
                        data-currency="eur"
                        data-locale="auto"></script>
            <% end %>

        <%end%> 
    
</div> 
<div class="shadow mt-5 p-5 bg-light"> 
    <table class="table table-striped table-dark"> 
        <thead> 
            <tr class="bg-primary"> 
                <th scope="col">
                    #
                </th> 
                <th scope="col">Invités</th> 
                <th scope="col"></th> 
            </tr> 
        </thead> 
        <tbody>  
            <% @attendees.each do |a| %> 
                <tr> 
                    <th scope="row"><%= a.id%></th> 
                    <td><%= a.email %></td> 
                    <td><%= link_to "Voir", user_show_path(a.id), class: 'btn btn-info' %></td> 
                </tr> <% end %> 
        </tbody> 
    </table> 
</div>

app/views/home/index.html.erb
<h1>Bienvenue dans notre site </h1>

app/views/home/show.html.erb
<h1> <%= link_to "Se deconnecter", destroy_user_session_path, :method => 'delete' %></h1>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-dark shadow" style="background-color: #373634">
    <a class="navbar-brand" href="<%= home_path %>">Eventbrite Like </a> 
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" 
      aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
 
 <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav ml-auto">
        <li class="nav-item">
            <a class="nav-link" href="<%= home_path %>">Accueil</a>
        </li>
        <% if current_user %>
            <li class="nav-item">
                <a class="nav-link" href="<%= new_event_path %>">Créer un évènement</a>
            </li>
            <li class="nav-item">
                <%= link_to "Sign out", destroy_user_session_path, :method => 'delete' %>
            </li>
        <%end%>
    </ul>
    <form class="form-inline">

    </form>
  </div>
 </nav>
 

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>EventbriteDevise</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

    <%= render "layouts/header" %>

    
    <div class="container">
    <div>
      <p class="notice"> <%= notice %> </p>
      <p class="alert"> <%= alert %> </p>
      <%= yield %>
    </div>
    </div>

   <script
    src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
    integrity="sha256-3edrmyuQ0w65f8gfBsqowzjJe2iM6n0nKciPUp8y+7E="
    crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js">
   </script>
  </body>
</html>

app/views/users/show.html.erb
<div class="center jumbotron"> 
    <h1>User: <%= current_user.email %></h1> 
    <%= link_to "Retour au liste des evenement", home_path, class: "btn btn-lg btn-success" %> 
</div> 
<% if flash[:success] %> 
    <div class="alert alert-success alert-dismissible fade show" role="alert"> 
        <strong><%= flash[:success] %></strong> 
        <button type="button" class="close" data-dismiss="alert" aria-label="Close" > 
            <span aria-hidden="true">&times;</span> 
        </button> 
    </div> 
<% end %> 
<div class="shadow mt-5 p-5 bg-light"> 
    <h3>Listes des evenements crees</h3> 
    <table class="table table-striped table-dark"> 
        <thead> 
            <tr class="bg-danger"> 
                <th scope="col">
                    #
                </th> 
                <th scope="col">
                    Place
                </th> 
                <th scope="col">Description</th> 
                <th scope="col">Date</th> 
                <th scope="col"></th> 
            </tr> 
        </thead> 
        <tbody> 
            <% @events.each do |e| %> 
                <tr> 
                    <th scope="row"><%= e.id%></th> 
                    <td><%= e.place %></td> 
                    <td><%= e.description %></td> 
                    <td><%= Date.parse(e.date.to_s).strftime('%a %d %b %Y') %></td> 
                    <td><%= link_to "Voir", '', class: 'btn btn-info' %></td> 
                </tr> 
            <% end %> 
        </tbody> 
    </table> 
</div>

app/views/users/view_user.html.erb
<div class="center jumbotron"> 
    <h1>la liste des évenements auquel <%= @user.email %> participe</h1> 
</div> 
<div class="shadow mt-5 p-5 bg-light"> 
    <table class="table table-striped table-dark"> 
        <thead> 
            <tr class="bg-danger"> 
                <th scope="col">
                    #
                </th> 
                <th scope="col">Place</th> 
                <th scope="col">Description</th> 
                <th scope="col">Date</th> 
                <th scope="col"></th> 
            </tr> 
            </thead> 
            <tbody> 
                <% @events.each do |e| %> 
                    <tr> <th scope="row"><%= e.id%></th> 
                    <td><%= e.place %></td> 
                    <td><%= e.description %></td> 
                    <td><%= Date.parse(e.date.to_s).strftime('%a %d %b %Y') %></td> 
                    <td> <%= link_to "Voir", '', class: 'btn btn-info' %> 
                        <% 
                            i = 0 
                            @attendees.each do |a| 
                                if a.id == current_user.id 
                                    i += 1 
                                end 
                            end 
                            if i > 0 
                        %> 
                                <%= link_to "Vous êtes déjà inscrit", '#', class: "btn btn-info disabled" %> 
                            <% else %> 
                                <%= form_tag suscribe_path do %>
                                    <article>
                                    <% if flash[:error].present? %>
                                        <div id="error_explanation">
                                        <p><%= flash[:error] %></p>
                                        </div>
                                    <% end %>
                                    <label class="amount">
                                        <span>Participation : <%= e.price.to_f/100 %> eur</span>
                                    </label>
                                    </article>
                                
                                    <script src="https://checkout.stripe.com/checkout.js" class="stripe-button"
                                            data-key="<%= Rails.configuration.stripe[:publishable_key] %>"
                                            data-description="A month's subscription"
                                            data-amount="500"
                                            data-currency="eur"
                                            data-locale="auto"></script>
                                <% end %> 
                            <% end %> 
                            <!-- <%= link_to "Inviter un potos", invite_path(e.id), class: "btn btn-warning" %> -->
                    </td> 
                    </tr> 
                <% end %> 
            </tbody> 
        </table> 
    </div>